channels:
  - conda-forge
dependencies:
  - python=3.7
  - rise    
  - cython
  - ipython
  - ipyparallel
  - ipywidgets
  - numpy
  - matplotlib
  - mpi4py
  - networkx
  - pandas
  - scikit-image
  - scikit-learn
  - sympy
  - bokeh
  - pip:
    - jupyter-contrib-nbextensions
    - notebook==6.1.5
